version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.25.0
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.31.0
    - 5.34.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 6.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.4.0
    - 17.4.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 12.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.32.0
    - 5.33.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.1
    - 7.13.8
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
